apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lesson24_rolebind
subjects:
- kind: User
  name: lesson24
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: lesson24-role
  apiGroup: rbac.authorization.k8s.io
